# Generated by Django 5.0 on 2023-12-28 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_no', models.CharField(max_length=50)),
                ('vehicle_type', models.CharField(choices=[('--select type--', '--select type--'), ('two', 'Two wheelers'), ('three', 'three wheelers'), ('four', 'four wheelers')], default=1, max_length=50)),
                ('vehicle_model', models.CharField(max_length=50)),
                ('vehicle_desc', models.CharField(max_length=50)),
            ],
        ),
    ]
