# Generated by Django 4.2.2 on 2023-12-29 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('--select type--', '--select type--'), ('two', 'Two wheelers'), ('three', 'three wheelers'), ('four', 'four wheelers')], default='--select type--', max_length=50),
        ),
    ]
