# Generated by Django 5.0 on 2023-12-30 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_vehicle_vehicle_model_alter_vehicle_vehicle_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_model',
            field=models.TextField(),
        ),
    ]
